## READ DATASETS FROM [CSV,JSON,PARQUET ]

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\ghtfut\downloads\hanisri\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ghtfut\downloads\hanisri\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ghtfut\downloads\hanisri\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ghtfut\downloads\hanisri\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ghtfut\downloads\hanisri\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ghtfut\downloads\hanisri\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# CSV FILE

In [21]:
import pandas as pd

In [22]:
print(pd)

<module 'pandas' from 'C:\\Users\\ghtfut\\Downloads\\hanisri\\Lib\\site-packages\\pandas\\__init__.py'>

In [23]:
import pandas as pd

In [24]:
import os

In [25]:
import numpy as np

# READ DATASETS

In [26]:
csv_path=("C\\Users\\ghtfut\\Downloads\\hariniragunathan\\iris.csv")

In [27]:
df_csv=pd.read_csv("iris.csv")

In [28]:
print(df_csv.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

# SHOW LAST 5 ROWS

In [29]:
df_csv.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

## SHOW FIRST 5 ROWS

In [13]:
df_csv.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

## COLUMNS NAMES

In [14]:
df_csv.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

# DATA SET INFORMATION

In [15]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# DATASET SIZE

In [16]:
df_csv.shape

(150, 5)

# FIND MAXIMUM VAULE

In [17]:
df_csv.max()

sepal.length          7.9
sepal.width           4.4
petal.length          6.9
petal.width           2.5
variety         Virginica
dtype: object

# FIND MINIMUM VALUE

In [18]:
df_csv.min()

sepal.length       4.3
sepal.width        2.0
petal.length       1.0
petal.width        0.1
variety         Setosa
dtype: object

# SUMMARY STATISTICS

In [19]:
df_csv.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# CHECK MISSING VALUE

In [20]:
df_csv.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

# JSON FILE

# READ JSON FILE

In [30]:
df=pd.read_json("posts.json")

# READ DATASET FOR FIRST 10 ROWS

In [31]:
print(df.head)

<bound method NDFrame.head of     userId   id                                              title  \
0        1    1  sunt aut facere repellat provident occaecati e...
1        1    2                                       qui est esse
2        1    3  ea molestias quasi exercitationem repellat qui...
3        1    4                               eum et est occaecati
4        1    5                                 nesciunt quas odio
..     ...  ...                                                ...
95      10   96  quaerat velit veniam amet cupiditate aut numqu...
96      10   97         quas fugiat ut perspiciatis vero provident
97      10   98                        laboriosam dolor voluptates
98      10   99  temporibus sit alias delectus eligendi possimu...
99      10  100              at nam consequatur ea labore ea harum

                                                 body
0   quia et suscipit\nsuscipit recusandae consequu...
1   est rerum tempore vitae\nsequi sint nihil repr...
2   et iusto sed quo iure\nvoluptatem occaecati om...
3   ullam et saepe reiciendis voluptatem adipisci\...
4   repudiandae veniam quaerat sunt sed\nalias aut...
..                                                ...
95  in non odio excepturi sint eum\nlabore volupta...
96  eum non blanditiis soluta porro quibusdam volu...
97  doloremque ex facilis sit sint culpa\nsoluta a...
98  quo deleniti praesentium dicta non quod\naut e...
99  cupiditate quo est a modi nesciunt soluta\nips...

[100 rows x 4 columns]>

# CHECK INFORMATION

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userId  100 non-null    int64
 1   id      100 non-null    int64
 2   title   100 non-null    object
 3   body    100 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.3+ KB

# DELETE SPECIFIC COLUMNS

In [36]:
df.drop("body",axis=1)

    userId   id                                              title
0        1    1  sunt aut facere repellat provident occaecati e...
1        1    2                                       qui est esse
2        1    3  ea molestias quasi exercitationem repellat qui...
3        1    4                               eum et est occaecati
4        1    5                                 nesciunt quas odio
..     ...  ...                                                ...
95      10   96  quaerat velit veniam amet cupiditate aut numqu...
96      10   97         quas fugiat ut perspiciatis vero provident
97      10   98                        laboriosam dolor voluptates
98      10   99  temporibus sit alias delectus eligendi possimu...
99      10  100              at nam consequatur ea labore ea harum

[100 rows x 3 columns]

df.head(10)

# PARTICULAR COLUMN

In [40]:
df[["userId","title"]]

    userId                                              title
0        1  sunt aut facere repellat provident occaecati e...
1        1                                       qui est esse
2        1  ea molestias quasi exercitationem repellat qui...
3        1                               eum et est occaecati
4        1                                 nesciunt quas odio
..     ...                                                ...
95      10  quaerat velit veniam amet cupiditate aut numqu...
96      10         quas fugiat ut perspiciatis vero provident
97      10                        laboriosam dolor voluptates
98      10  temporibus sit alias delectus eligendi possimu...
99      10              at nam consequatur ea labore ea harum

[100 rows x 2 columns]

# PARQUET FILE

# READ DATASETS

In [41]:
df=pd.read_parquet("titanic.parquet")

In [42]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500  None        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250  None        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500  None        S

In [43]:
print(df.info)

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500  None        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250  None        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500  None        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000  None        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500  None        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500  None        Q

[891 rows x 12 columns]>

In [45]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [46]:
print(df.describe)

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500  None        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250  None        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500  None        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000  None        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500  None        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500  None        Q

[891 rows x 12 columns]>

In [47]:
print(df.shape)

(891, 12)